######################################################################
# Automatically generated by qmake (2.01a) Sa 27. Jan 20:01:57 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG	+= console release
QT	+= sql
DEFINES	+= QT_SIDE_BY_SIDE_ASSEMBLY
# Input
SOURCES += test.cpp
